modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "libgui"
version = "${version}"
displayName = "LibGui"
authors = "Falkreon and Juuz"
description = '''
TEasy grid-based GUIs for MultPlatform
'''
logoFile = "assets/libgui/icon.png"

[[dependencies.libgui]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.libgui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.libgui]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
